# Tutorial PAMAP2 with mcfly

The goal of this tutorial is to get you familiar with training Neural Networks for time series using mcfly. At the end of the tutorial, you will have compared several Neural Network architectures you know how to train the best performing network.

As an example dataset we use the publicly available [PAMAP2 dataset](https://archive.ics.uci.edu/ml/datasets/PAMAP2+Physical+Activity+Monitoring). It contains time series data from movement sensors worn by nine individuals. The data is labelled with the activity types that these individuals did and the aim is to train and evaluate a *classifier*.

Before you can start, please make sure you install mcfly (see the [mcfly installation page](https://github.com/NLeSC/mcfly)).

## Import required Python modules

In [86]:
import sys
import os
import json
import numpy as np
import pandas as pd
import mcfly
from mcfly.find_architecture import train_models_on_samples
from sklearn.model_selection import train_test_split
from sktime.datasets import load_from_tsfile
import tensorflow as tf
import warnings
import dill

warnings.filterwarnings('ignore')
np.random.seed(2)

In [ ]:
# deprecated
# sys.path.insert(0, os.path.abspath('../..'))
# from utils import tutorial_pamap2

## Download data pre-procesed data

We have created a function for you to fetch the preprocessed data from https://zenodo.org/record/834467. Please specify the `directory_to_extract_to` in the code below and then execute the cell. This will download the preprocessed data into the directory in the `data` subdirectory. The output of the function is the path where the preprocessed data was stored.

In [2]:
# Specify in which directory you want to store the data:
directory_to_extract_to = '../'

In [ ]:
!ls -l ../data/Predictive-Maintenance-Of-Hydraulics-System

In [3]:
# data_path = tutorial_pamap2.download_preprocessed_data(directory_to_extract_to)
# data_path = '../data/PAMAP2/PAMAP2/preprocessed'
data_path = '../data/Predictive-Maintenance-Of-Hydraulics-System'

## A bit about the data

The [PAMAP2 dataset](https://archive.ics.uci.edu/ml/datasets/PAMAP2+Physical+Activity+Monitoring) contains data from three movement sensors worn by nine test subjects. These subjects performed a protocol of several activities.

The data originates from three sensors (on the hand, ankle and chest) and from each of the sensors we have three channels (acceleration on x, y and z axes). This gives us, for each time step, 9 values. The data is recorded on 100 Hz.

The preprocessed data is split into smaller segments with a window of 512 time steps, corresponding to 5.12 seconds. We only include segments that completely fall into one activity period: the activity is the *label* of the segment.

The goal of classification is to assign an activity label to an previously unseen segment.

## Load the pre-processed data

Load the preprocessed data as stored in Numpy-files. Please note that the data has already been split up in a training (training), validation (val), and test subsets. It is common practice to call the input data X and the labels y.

In [4]:
X = np.load(f'{data_path}/preprocessed.npy')
targets = pd.read_csv(f'{data_path}/profile_targets.csv')

In [5]:
X = np.swapaxes(X, 1, 2)
X.shape

(2205, 60, 17)

In [6]:
targets.head()

target_cooler_condition  target_valve_condition  \
0                        3                     100   
1                        3                     100   
2                        3                     100   
3                        3                     100   
4                        3                     100   

   target_internal_pump_leakage  target_hydraulic_accumulator_pressure  \
0                             0                                    130   
1                             0                                    130   
2                             0                                    130   
3                             0                                    130   
4                             0                                    130   

   target_stable_flag  
0                   1  
1                   1  
2                   1  
3                   1  
4                   1

In [7]:
targets['target_cooler_condition'].value_counts()

100    741
3      732
20     732
Name: target_cooler_condition, dtype: int64

In [8]:
codes, uniques = targets['target_cooler_condition'].factorize()
y_binary = tf.keras.utils.to_categorical(codes, num_classes=len(uniques))

In [9]:
X_train, X_test, y_train_binary, y_test_binary = train_test_split(X, y_binary, test_size=0.10, random_state=42)

X_train.shape, X_test.shape, y_train_binary.shape, y_test_binary.shape


((1984, 60, 17), (221, 60, 17), (1984, 3), (221, 3))

In [10]:
X_train, X_val, y_train_binary, y_val_binary = train_test_split(X_train, y_train_binary, test_size=0.20, random_state=42)

X_train.shape, X_val.shape, y_train_binary.shape, y_val_binary.shape

((1587, 60, 17), (397, 60, 17), (1587, 3), (397, 3))

In [ ]:
# X_train, y_train_binary, X_val, y_val_binary, X_test, y_test_binary, labels = tutorial_pamap2.load_data(data_path)

X_train = np.load(f'{data_path}/X_train.npy')
y_train_binary = np.load(f'{data_path}/y_train.npy')
X_val = np.load(f'{data_path}/X_val.npy')
y_val_binary = np.load(f'{data_path}/y_val.npy')
X_test = np.load(f'{data_path}/X_test.npy')
y_test_binary = np.load(f'{data_path}/y_test.npy')

In [ ]:
with open(os.path.join(data_path, 'labels.json'), 'r') as fn:
    labels = json.load(fn)

Data X and labels y are of type Numpy array. In the cell below we inspect the shape of the data. As you can see the shape of X is expressed as a Python tuple containing: the number of samples, length of the time series, and the number of channels for each sample. Similarly, the shape of y is represents the number of samples and the number of classes (unique labels). Note that y has the format of a binary array where only the correct class for each sample is assigned a 1. This is called one-hot-encoding.

In [17]:
print('x shape:', X_train.shape)
print('y shape:', y_train_binary.shape)

x shape: (1587, 60, 17)
y shape: (1587, 3)


In [ ]:
# reshape ts file to fit the mcfly input shape requirement 
# xs = X_train.shape
# X_train.reshape((xs[0], xs[2],xs[1])).shape
# Output: (11397, 9, 512)

The data is split between train test and validation.

In [18]:
print('train set size:', X_train.shape[0])
print('validation set size:', X_val.shape[0])
print('test set size:', X_test.shape[0])

train set size: 1587
validation set size: 397
test set size: 221


Let's have a look at the distribution of the labels:

In [ ]:
# frequencies = y_train_binary.mean(axis=0)
# frequencies_df = pd.DataFrame(frequencies, index=labels, columns=['frequency'])
# frequencies_df

### *Question 1: How many channels does this dataset have?*
### *Question 2: What is the least common activity label in this dataset?*

    

## Generate models

First step in the development of any deep learning model is to create a model architecture. As we do not know what architecture is best for our data we will create a set of random models to investigate which architecture is most suitable for our data and classification task. This process, creating random models, checking how good they are and then selecting the best one is called a 'random search'. A random search is considered to be the most robust approach to finding a good model. You will need to specificy how many models you want to create with argument 'number_of_models'. See for a full overview of the optional arguments the function documentation of modelgen.generate_models by running `modelgen.generate_models?`.

##### What number of models to select?
This number differs per dataset. More models will give better results but it will take longer to evaluate them. For the purpose of this tutorial we recommend trying only 2 models to begin with. If you have enough time you can try a larger number of models, e.g. 10 or 20 models. Because mcfly uses random search, you will get better results when using more models.

In [ ]:
num_classes = y_train_binary.shape[1]
metric = 'binary_accuracy' # 'accuracy'
models = mcfly.modelgen.generate_models(X_train.shape,
                                        number_of_classes=num_classes,
                                        number_of_models = 1,
                                        metrics=[metric])

# Inspect the models
We can have a look at the models that were generated. The layers are shown as table rows. Most common layer types are 'Convolution' and 'LSTM' and 'Dense'. For more information see the [mcfly user manual](https://github.com/NLeSC/mcfly/wiki/User-manual) and the [tutorial cheat sheet](https://github.com/NLeSC/mcfly-tutorial/blob/master/cheatsheet.md). The summary also shows the data shape of each layer output and the number of parameters that are trained within this layer.

In [ ]:
models_to_print = range(len(models))
for i, item in enumerate(models):
    if i in models_to_print:
        model, params, model_types = item
        print("-------------------------------------------------------------------------------------------------------")
        print("Model " + str(i))
        print(" ")
        print("Hyperparameters:")
        print(params)
        print(" ")
        print("Model description:")
        model.summary()
        print(" ")
        print("Model type:")
        print(model_types)
        print(" ")

### *Question 3: Can you guess what hyperparameter 'learning rate' stands for?*

## Compare models
Now that the model architectures have been generated it is time to compare the models by training them on a subset of the training data and evaluating the models on the validation subset. This will help us to choose the best candidate model. The performance results for the models are stored in a json file, which we will visually inspect later on.

In [ ]:
# Define directory where the results, e.g. json file, will be stored
resultpath = os.path.join(directory_to_extract_to, 'models')
if not os.path.exists(resultpath):
        os.makedirs(resultpath)

We are now going to train each of the models that we generated. On the one hand we want to train them as quickly as possible in order to be able to pick the best one as soon as possible. On the other hand we have to train each model long enough to get a good impression of its potential.

We can influence the train time by adjusting the number of data samples that are used. This can be set with the argument 'subset_size'. We can also adjust the number of times the subset is iterated over. This number is called an epoch. We recommend to start with no more than 5 epochs and a maximum subset size of 300. You can experiment with these numbers.

In [ ]:
outputfile = os.path.join(resultpath, 'modelcomparison.json')
histories, val_accuracies, val_losses = train_models_on_samples(X_train, 
                                                                y_train_binary,
                                                                X_val, 
                                                                y_val_binary,
                                                                models,
                                                                nr_epochs=5,
                                                                subset_size=1000,
                                                                verbose=True,
                                                                outputfile=outputfile,
                                                                metric=metric)

print('Details of the training process were stored in ',outputfile)

### *Question 4: What does the term 'loss' in the output refer to?*

# Inspect model performance (Visualization)

We can inspect the learning process in the visualization tool on http://nlesc.github.io/mcfly/.

Alternatively, you can run the visualization from a local web service:
- Clone the mcfly github repository (if you haven't done so already for visualization)

 `git clone https://github.com/NLeSC/mcfly`


- navigate to the html folder:

 `cd mcfly/html`


- Start a web server. This can be done in various ways, for example:
 - for python 3 you can use: `python3 -m http.server`
 - for python 2 you can use: `python2 -m SimpleHTTPServer`

Notice the port number the web server is serving on. This is usually 8000.
With a web browser, navigate to [localhost:8000](localhost:8000). 

You need to upload the json file that contains the details of the training process. The following line of code shows the path to this file:

In [ ]:
outputfile

### *Question 5:  Look at the visualization. Which model performs best?*
### *Question 6:  Did you train all models with a sufficient number of iterations?*

# Inspect model performance (table)

Let's compare the performance of the models by showing the results as a table.

In [ ]:
# metric = 'accuracy'
modelcomparisons = pd.DataFrame({'model':[str(params) for model, params, model_types in models],
                       'train_{}'.format(metric): [history.history[metric][-1] for history in histories],
                       'train_loss': [history.history['loss'][-1] for history in histories],
                       'val_{}'.format(metric): [history.history['val_{}'.format(metric)][-1] for history in histories],
                       'val_loss': [history.history['val_loss'][-1] for history in histories]
                       })
modelcomparisons.to_csv(os.path.join(resultpath, 'modelcomparisons.csv'))

modelcomparisons

In [ ]:
modelcomparisons.iloc[0,0]

# Choose the best model
Now that we found an effective architecture, we can choose the most promising model. For example, we can choose the model with the highest accuracy on the validation data set. To maximize this models performance, we will train this model on more data and more epochs.

In [ ]:
best_model_index = np.argmax(val_accuracies)
best_model, best_params, best_model_types = models[best_model_index]
print('Model type and parameters of the best model:')
print(best_model_types)
print(best_params)

## Train the best model on the full dataset

Now that we have identified the best model architecture out of our random pool of models we can continue by training the model on the full training set.

This would take some time, so instead we will train  on only a slightly larger subset.

In [ ]:
X_train.shape[0]

In [ ]:
#We make a copy of the model, to start training from fresh
nr_epochs = 5
datasize = X_train.shape[0] # Change in `X_train.shape[0]` if training complete data set

history = best_model.fit(
    X_train[:datasize,:,:], 
    y_train_binary[:datasize,:],
    epochs=nr_epochs, 
    validation_data=(X_val, y_val_binary)
)

### *Question 7: Why does it take longer to train the best model for one epoch now than when we were  comparing model archicatures earlier on?*

### *Question 8: Do you think it is useful to train with more than 1 epoch?*

### Saving, loading and comparing reloaded model with original model

The model can be saved for future use. The savemodel function will save two separate files: a json file for the architecture and a npy (numpy array) file for the weights.

In [ ]:
modelname = 'my_bestmodel.h5'
model_path = os.path.join(resultpath,modelname)

In [ ]:
best_model.save(model_path)

In [ ]:
model_reloaded = tf.keras.models.load_model(model_path)

The model has been reloaded. Let's reassure that this model has the same weights

In [ ]:
np.all([np.all(x==y) for x,y in zip(best_model.get_weights(), model_reloaded.get_weights())])

## Investigate model predictions

We will now dive further into the Neural network that we created.
We provide here a network that has been trained on the complete train set.

In [ ]:
model = tf.keras.models.load_model('./model/model.h5')

Note that the objects `models`, `best_model_fullytrained` and `best_model` that resulted from the mcfly functions are Keras objects. This means that you can use Keras functions on the objects, for example  `.predict`, (which when given the data, outputs the predictions for each sample) and `.evaluate` (which when given the data and the labels computes how well this model performs) . These functions are all documented in the [Keras documentation](https://www.tensorflow.org/api_docs/python/tf/keras). 

In [ ]:
## Inspect model predictions on validation data
datasize = X_val.shape[0]
probs = model.predict(X_val[:datasize,:,:],batch_size=1)

Let's have a look at the [confusion matrix](https://en.wikipedia.org/wiki/Confusion_matrix)

In [ ]:
#columns are predicted, rows are truth
predicted = probs.argmax(axis=1)
y_index = y_val_binary.argmax(axis=1)
confusion_matrix = pd.crosstab(pd.Series(y_index), pd.Series(predicted))
confusion_matrix.index = [labels[i] for i in confusion_matrix.index]
confusion_matrix.columns = [labels[i] for i in confusion_matrix.columns]
confusion_matrix.reindex(columns=[l for l in labels], fill_value=0)
confusion_matrix

In [ ]:
## Test on Testset
score_test = model.evaluate(X_test, y_test_binary, verbose=True)
print('Score of best model: ' + str(score_test))

## Find Best Architecture

## mcfly.find_architecture.find_best_architecture

In [19]:
from mcfly.find_architecture import find_best_architecture

In [22]:
best_model, best_params, best_model_type, knn_acc = \
            find_best_architecture(
                X_train=X_train,
                y_train=y_train_binary,
                X_val=X_val,
                y_val=y_val_binary, 
                number_of_models=5,
                nr_epochs=20,
                subset_size=5000,
            )

Set maximum kernel size for InceptionTime models to number of timesteps.
Generated models will be trained on subset of the data (subset size: 5000).
Training model 0 DeepConvLSTM
Epoch 1/20
80/80 [==============================] - 13s 122ms/step - loss: 3.4759 - accuracy: 0.9275 - val_loss: 1.7112 - val_accuracy: 0.6574
Epoch 2/20
80/80 [==============================] - 9s 109ms/step - loss: 0.6624 - accuracy: 0.9502 - val_loss: 1.0053 - val_accuracy: 0.6499
Epoch 3/20
80/80 [==============================] - 9s 107ms/step - loss: 0.3255 - accuracy: 0.9609 - val_loss: 0.5266 - val_accuracy: 0.8438
Epoch 4/20
80/80 [==============================] - 9s 107ms/step - loss: 0.2728 - accuracy: 0.9685 - val_loss: 0.2304 - val_accuracy: 0.9975
Epoch 5/20
80/80 [==============================] - 9s 107ms/step - loss: 0.3449 - accuracy: 0.9635 - val_loss: 0.2731 - val_accuracy: 0.9975
Epoch 6/20
80/80 [==============================] - 10s 124ms/step - loss: 0.2778 - accuracy: 0.9748 - val_los

In [23]:
best_model

In [ ]:
model_path = os.path.join('../data', 'best_model')

best_model.save(model_path)

In [ ]:
reconstructed_model = tf.keras.models.load_model(model_path)

In [ ]:
y_pred = reconstructed_model.predict(X_val)

In [ ]:
y_pred[0:5]

In [ ]:
print(np.argmax(y_pred))

In [ ]:
y_pred.argmax(axis=1)

In [ ]:
#We make a copy of the model, to start training from fresh
nr_epochs = 20
datasize = X_train.shape[0] # Change in `X_train.shape[0]` if training complete data set

history = best_model.fit(
    X_train[:datasize,:,:], 
    y_train_binary[:datasize,:],
    epochs=nr_epochs, 
    validation_data=(X_val, y_val_binary)
)

In [26]:
## Test on Testset
score_test = best_model.evaluate(X_test, y_test_binary, verbose=True)
print('Score of best model: ' + str(score_test))

7/7 [==============================] - 0s 58ms/step - loss: 0.1417 - accuracy: 1.0000
Score of best model: [0.14174917340278625, 1.0]


In [26]:
a = np.array([[[91, 92, 93], [49, 59, 69]], 
              [[10, 20, 30], [40, 50, 60]]])

print('a.shape ==', a.shape)
display(a)

a.shape == (2, 2, 3)


array([[[91, 92, 93],
        [49, 59, 69]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [27]:
b = np.swapaxes(a, 1, 2)
print('b.shape ==', b.shape)
display(b)

b.shape == (2, 3, 2)


array([[[91, 49],
        [92, 59],
        [93, 69]],

       [[10, 40],
        [20, 50],
        [30, 60]]])

In [28]:
from sklearn.preprocessing import OneHotEncoder

In [44]:
enc = OneHotEncoder(handle_unknown='ignore')

In [32]:
X = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(X)

OneHotEncoder(handle_unknown='ignore')

In [33]:
enc.transform([['Female', 1], ['Male', 4]]).toarray()

array([[1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [34]:
profile = pd.read_csv('../data/Predictive-Maintenance-Of-Hydraulics-System/profile_targets.csv')
profile.head()

target_cooler_condition  target_valve_condition  \
0                        3                     100   
1                        3                     100   
2                        3                     100   
3                        3                     100   
4                        3                     100   

   target_internal_pump_leakage  target_hydraulic_accumulator_pressure  \
0                             0                                    130   
1                             0                                    130   
2                             0                                    130   
3                             0                                    130   
4                             0                                    130   

   target_stable_flag  
0                   1  
1                   1  
2                   1  
3                   1  
4                   1

In [36]:
labels = profile['target_hydraulic_accumulator_pressure'].unique()
labels

array([130, 115, 100,  90])

In [40]:
keys = [str(x) for x in labels]
keys

['130', '115', '100', '90']

In [43]:
class_labels = []

for k, l in zip(keys, labels):
    class_labels.append([k , l])

class_labels

[['130', 130], ['115', 115], ['100', 100], ['90', 90]]

In [45]:
enc.fit(class_labels)

OneHotEncoder(handle_unknown='ignore')

In [46]:
enc.transform([['130', 130]]).toarray()

array([[0., 0., 1., 0., 0., 0., 0., 1.]])

In [51]:
labels_binary = pd.get_dummies(['130', '115', '100', '90', '130', '100'])
labels_binary.to_numpy()

array([[0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0]], dtype=uint8)

In [57]:
df_labels = pd.DataFrame(keys, columns=['label'])
df_labels

label
0   130
1   115
2   100
3    90

In [60]:
df_labels['label'].to_numpy().reshape(-1, 1)

array([['130'],
       ['115'],
       ['100'],
       ['90']], dtype=object)

In [52]:
labels_binary.idxmax(axis=1)

0    130
1    115
2    100
3     90
4    130
5    100
dtype: object

In [ ]:
label_encoder = OneHotEncoder(handle_unknown='ignore')
transformed = label_encoder.transform(df_labels['label'].to_numpy().reshape(-1, 1))

In [67]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
lb.fit_transform(['100', '115', '130', '90', '115', '130', '100', '130'])


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0]])

In [64]:
lb.classes_

array(['100', '115', '130', '90'], dtype='<U3')

In [68]:
lb.transform(['130', '90', '90', '90', '90', '115'])

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 1, 0, 0]])

In [72]:
np.concatenate((np.array([1,2,3]), np.array([11,2,31])))

array([ 1,  2,  3, 11,  2, 31])

In [73]:
from sktime.datasets import load_basic_motions

In [74]:
X, y = load_basic_motions(return_X_y=True)

In [77]:
display(X.head())

dim_0  \
0  0     0.079106
1     0.079106
2    -0.903497
3...   
1  0     0.377751
1     0.377751
2     2.952965
3...   
2  0    -0.813905
1    -0.813905
2    -0.424628
3...   
3  0     0.289855
1     0.289855
2    -0.669185
3...   
4  0    -0.123238
1    -0.123238
2    -0.249547
3...   

                                               dim_1  \
0  0     0.394032
1     0.394032
2    -3.666397
3...   
1  0    -0.610850
1    -0.610850
2     0.970717
3...   
2  0     0.825666
1     0.825666
2    -1.305033
3...   
3  0     0.284130
1     0.284130
2    -0.210466
3...   
4  0     0.379341
1     0.379341
2     0.541501
3...   

                                               dim_2  \
0  0     0.551444
1     0.551444
2    -0.282844
3...   
1  0    -0.147376
1    -0.147376
2    -5.962515
3...   
2  0     0.032712
1     0.032712
2     0.826170
3...   
3  0     0.213680
1     0.213680
2     0.252267
3...   
4  0    -0.286006
1    -0.286006
2     0.208420
3...   

                                               dim_3  \
0  0     0.351565
1     0.351565
2    -0.095881
3...   
1  0    -0.103872
1    -0.103872
2    -7.593275
3...   
2  0     0.021307
1     0.021307
2    -0.372872
3...   
3  0    -0.314278
1    -0.314278
2     0.018644
3...   
4  0    -0.098545
1    -0.098545
2    -0.023970
3...   

                                               dim_4  \
0  0     0.023970
1     0.023970
2    -0.319605
3...   
1  0    -0.109198
1    -0.109198
2    -0.697804
3...   
2  0     0.122515
1     0.122515
2    -0.045277
3...   
3  0     0.074574
1     0.074574
2     0.007990
3...   
4  0     0.058594
1     0.058594
2     0.175783
3...   

                                               dim_5  
0  0     0.633883
1     0.633883
2     0.972131
3...  
1  0    -0.037287
1    -0.037287
2    -2.865789
3...  
2  0     0.775041
1     0.775041
2     0.383526
3...  
3  0    -0.079901
1    -0.079901
2     0.237040
3...  
4  0    -0.074574
1    -0.074574
2     0.114525
3...

In [78]:
display(y)

array(['Standing', 'Standing', 'Standing', 'Standing', 'Standing',
       'Standing', 'Standing', 'Standing', 'Standing', 'Standing',
       'Running', 'Running', 'Running', 'Running', 'Running', 'Running',
       'Running', 'Running', 'Running', 'Running', 'Walking', 'Walking',
       'Walking', 'Walking', 'Walking', 'Walking', 'Walking', 'Walking',
       'Walking', 'Walking', 'Badminton', 'Badminton', 'Badminton',
       'Badminton', 'Badminton', 'Badminton', 'Badminton', 'Badminton',
       'Badminton', 'Badminton', 'Standing', 'Standing', 'Standing',
       'Standing', 'Standing', 'Standing', 'Standing', 'Standing',
       'Standing', 'Standing', 'Running', 'Running', 'Running', 'Running',
       'Running', 'Running', 'Running', 'Running', 'Running', 'Running',
       'Walking', 'Walking', 'Walking', 'Walking', 'Walking', 'Walking',
       'Walking', 'Walking', 'Walking', 'Walking', 'Badminton',
       'Badminton', 'Badminton', 'Badminton', 'Badminton', 'Badminton',
       'Badmin

In [81]:
np.unique(y)

array(['Badminton', 'Running', 'Standing', 'Walking'], dtype='<U9')

In [100]:
json_configuration = {
    "file_name": "hydraulic-systems-monitoring.ts", 
    "session_id": 2, 
    "file_location": "../data/Predictive-Maintenance-Of-Hydraulics-System/hydraulic-systems-monitoring/", 
    "task": 3, 
    "test_configuration": {"split_ratio": 0.8, "method": 0, "random_state": 42    }, 
    "tabular_configuration": {
        "target": {"target": "target", "type": 0}, 
        "features": {"dim_0": 0}
    }, 
    "file_configuration": {}, 
    "runtime_constraints": {"runtime_limit": 180, "max_iter": 0}, "metric": ""}


In [101]:
from enum import Enum, unique

class SplitMethod(Enum):
    SPLIT_METHOD_RANDOM = 0
    SPLIT_METHOD_END = 1

In [102]:
def get_config_property(output_path):
    return f'./{output_path}'


def read_panel_dataset_training_data(json_configuration):
    # Read the panel data
    X, y = load_from_tsfile(os.path.join(json_configuration["file_location"], json_configuration["file_name"]))
    
    # Create a label encoder
    label_binarizer = LabelBinarizer()
    label_binarizer.fit(y)
    
    
    file_name = 'label_binarizer.p'
    
    with open(os.path.join(get_config_property('output-path'), 'tmp', file_name), 'wb+') as file:
        dill.dump(lb, file)
    
    
    # split training set
    if SplitMethod.SPLIT_METHOD_RANDOM == json_configuration["test_configuration"]["method"]:
        X_train, X_test, y_train, y_test = train_test_split(X, 
                                                            y, 
                                                            train_size=json_configuration["test_configuration"]["split_ratio"], 
                                                            shuffle=True,
                                                            random_state=json_configuration["test_configuration"]["random_state"])
    else:
        X_train, X_test, y_train, y_test = train_test_split(X, 
                                                            y, 
                                                            train_size=json_configuration["test_configuration"]["split_ratio"], 
                                                            shuffle=False)
    return X_train, y_train, label_binarizer

In [93]:
!mkdir -p ./output-path/tmp

In [96]:
!ls -l ./output-path/tmp

total 4
-rw-r--r-- 1 us3r us3r 358 Jun  5 12:08 label_binarizer.p


In [103]:
X_train, y_train, label_binarizer = read_panel_dataset_training_data(json_configuration)

In [107]:
transformed = label_binarizer.transform(y_train)
transformed

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       ...,
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [105]:
label_binarizer.classes_

array(['100', '20', '3'], dtype='<U3')

In [111]:
pd.DataFrame(label_binarizer.inverse_transform(transformed[0:10]), columns=['predicted'])

predicted
0         3
1         3
2         3
3         3
4         3
5         3
6         3
7         3
8         3
9         3

In [112]:
from sklearn.metrics import mean_squared_error, accuracy_score

In [114]:
accuracy_score(['A', 'C', 'A', 'B', 'D'], ['A', 'C', 'C', 'B', 'D'])

0.8

In [119]:
20//10

2